### PR TITLE
Update libusb-sys version

### PR DESCRIPTION
**Pull request by Yatekii**

### CODE REVIEW

**Comment by tanriol** [comment]
Merged and released, thank you for contribution :-)

**Comment by Yatekii** [comment]
Would you mind cutting a release with this? :) I will gladly PR it if it helps :)

**Comment by tanriol** [comment]
@Yatekii I've published version 1.1.2 with this change yesterday. Have I made some mistake?..

**Comment by Yatekii** [comment]
Ah, I just checked master for a version bump :) Might be you did not push yet :)

**Comment by tanriol** [comment]
Thank you, pushed now :-)

**Pull request merged**
