### PR TITLE
cleanups and 1.0.0 preparation

### PR DESCRIPTION
**Pull request by tanriol**
Build on #4, but drop the vendored copy and everything specific to it.

### CODE REVIEW

**Comment by cr1901** [comment]
Re: e73dd1d, I didn't know that `include!` would actually work (b/c are relative `include!` paths relative to the current source file or the compiler invocation directory?)! If it works, fine w/ me!

**Comment by tanriol** [comment]
It's documented to be relative to the current file. Yes, it compiles :-)

**Comment by cr1901** [comment]
@tanriol Ahhh, awesome. LGTM aside from the bindgen blurb (should be disabled by default, correct?)!

**Comment by tanriol** [comment]
By the way, I'm not doing this right now in this PR, but we seem to be missing [quite a number of constants](https://www.intra2net.com/en/developer/libftdi/documentation/ftdi_8h.html) from the API.

**Comment by cr1901** [comment]
I swear, by the time I'm doing tweaking bindgen so that it actually emits the correct code, I could've written these bindings by hand in less time lmao. Uhhh, I'll take a look either tonight or tomorrow...

**Comment by tanriol** [comment]
Does not matter at the moment, I think... no one has asked for them yet :-)

**Pull request merged**
